name: "build-test-dev"
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Setup MSBuild (vswhere-path)
      id: setup_msbuild_explicit
      uses: ./
      with:
        vswhere-path: C:\ProgramData\chocolatey\bin

    - name: Setup MSBuild (PATH)
      id: setup_msbuild_path
      uses: ./

    - name: Setup MSBuild (fallback)
      id: setup_msbuild_fallback
      uses: ./
      env:
        PATH: ''

    - name: Setup MSBuild (x64)
      if: always()
      id: setup_msbuild_path_x64
      uses: ./
      with:
        vs-prerelease: true
        msbuild-architecture: 'x64'

    - name: echo msbuild path
      run: |
        echo "vswhere-path: ${{ steps.setup_msbuild_explicit.outputs.msbuildPath }}"
        echo "PATH: ${{ steps.setup_msbuild_path.outputs.msbuildPath }}"
        echo "x64 PATH: ${{ steps.setup_msbuild_path_x64.outputs.msbuildPath }}"
        echo "Fallback: ${{ steps.setup_msbuild_fallback.outputs.msbuildPath }}"

    - name: echo MSBuild
      run: msbuild -version

  build-arm64:
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v6

    - name: Setup MSBuild (arm64)
      id: setup_msbuild_path_arm
      uses: ./
      with:
        vs-prerelease: true
        msbuild-architecture: 'arm64'

    - name: echo msbuild path
      run: |
        echo "ARM64 PATH: ${{ steps.setup_msbuild_path_arm.outputs.msbuildPath }}"

    - name: echo MSBuild
      run: msbuild -version
